### ISSUE TITLE
Support for sending of email notification to known email address

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#148]
## Notification: Send email

This epic collects all issues related to the initial development of a notification system. It should be able to take an order to send an email notification to a provided email address. Included in this work we also will need to create the base infrastructure and architecture for additional services related to notifications.

### Considerations

Why don't the clients post directly to Kafka? As we know we will need authorization and authentication as well as some confirmation that the receipient is someone we can reach (at the moment of the creating the notification) we would need a library with all this logic bundled in. As we would have to provide libraries in different programming languages we believe a better approach is to provide an API with this functionality what we control and can modify as we see fit, in a single programming language. 

![image](https://github.com/Altinn/altinn-notifications/assets/47737608/824e5d2e-5c4e-4ed8-8f11-bc8028a9f7df)

### Deployment checklist

- [x] Create domains for communication services
- [x] Connect domain to communication services
- [x] Ensure alerts for notifications and notifications email are deployed

### Kafka service
The Kafka service being added to platform should be accessible for any use by any platform application. In other words, not restricted to Notification. 

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-notifications/issues/168
- [ ] https://github.com/Altinn/altinn-notifications/issues/167
- [ ] https://github.com/Altinn/altinn-notifications/issues/177
- [ ] https://github.com/Altinn/altinn-notifications/issues/155
- [ ] https://github.com/Altinn/altinn-notifications/issues/319
- [ ] https://github.com/Altinn/altinn-notifications/issues/284
- [ ] https://github.com/Altinn/altinn-notifications/issues/316
```

### Notifications micro service
This application should be the core part and access point for the Notification system. Primary objective is to take notification orders and provide endpoints for accessing stored notifications and their statuses. The API should have endpoints for both external and internal (within notifications) systems.

```[tasklist]
### Tasks
- [ ] #106
- [ ] https://github.com/Altinn/altinn-notifications/issues/107
- [ ] https://github.com/Altinn/altinn-notifications/issues/156
- [ ] https://github.com/Altinn/altinn-notifications/issues/161
- [ ] #62
- [ ] https://github.com/Altinn/altinn-notifications/issues/175
- [ ] https://github.com/Altinn/altinn-notifications/issues/163
- [ ] https://github.com/Altinn/altinn-notifications/issues/164
- [ ] #185
- [ ] https://github.com/Altinn/altinn-notifications/issues/193
- [ ] https://github.com/Altinn/altinn-notifications/issues/194
- [ ] https://github.com/Altinn/altinn-notifications/issues/197
- [ ] #160
- [ ] https://github.com/Altinn/altinn-notifications/issues/246
- [ ] https://github.com/Altinn/altinn-notifications/issues/245
- [ ] https://github.com/Altinn/altinn-notifications/issues/247
- [ ] https://github.com/Altinn/altinn-notifications/issues/166
- [ ] https://github.com/Altinn/altinn-notifications/issues/165
- [ ] https://github.com/Altinn/altinn-notifications/issues/264
- [ ] https://github.com/Altinn/altinn-notifications/issues/262
- [ ] https://github.com/Altinn/altinn-notifications/issues/253
- [ ] #8
- [ ] https://github.com/Altinn/altinn-notifications/issues/268
- [ ] https://github.com/Altinn/altinn-notifications/issues/265
- [ ] https://github.com/Altinn/altinn-notifications/issues/266
- [ ] https://github.com/Altinn/altinn-notifications/issues/267
- [x] Validation of email address. Use the same regex as in Altinn 2 as a start
- [x] Enable use case for remaining at envs, tt, and prod
- [ ] Ensure alert rules (AKS) are deployed to all environments
```

### Send email notification service

```[tasklist]
### Tasks
- [ ] #108
- [ ] https://github.com/Altinn/altinn-notifications/issues/150
- [ ] https://github.com/Altinn/altinn-notifications/issues/151
- [ ] https://github.com/Altinn/altinn-notifications/issues/152
- [ ] https://github.com/Altinn/altinn-notifications/issues/160
- [ ] https://github.com/Altinn/altinn-notifications/issues/158
- [ ] https://github.com/Altinn/altinn-notifications/issues/154
- [ ] https://github.com/Altinn/altinn-notifications/issues/159
- [ ] https://github.com/Altinn/altinn-notifications-email/issues/25
- [ ] https://github.com/Altinn/altinn-notifications/issues/261
- [ ] https://github.com/altinn/altinn-notifications-email/issues/33
- [ ] https://github.com/Altinn/altinn-notifications/issues/153
```

### Onboarding

Issues related to onboarding of existing users of the Altinn 2 notification system over to the new service

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-notifications/issues/276
- [ ] https://github.com/Altinn/altinn-notifications/issues/239
```

Obsolete sketch

![notifications-architecture drawio](https://github.com/Altinn/altinn-notifications/assets/47737608/2ad1e5e5-b8b7-4187-957e-77d8d560bac8)

![notifications-architecture drawio (1)](https://user-images.githubusercontent.com/47737608/235911774-27ef8b34-02de-49ba-a29a-99e701abbfc9.png)

**Comment by SandGrainOne** [comment]
All related issues and tasks have been completed.
