### ISSUE TITLE
App logic to send an email based on an event. Publish end result as an event.

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#152]
## Description

When a notification id is retrieved from Kafka the email service should 
(1) request additional information on the notification through the Notification API 
(2) build a send e-mail request using the properties from the notification 
(3) send the e-mail through the external email service client 
(4) report back on status of the sending of the e-mail through the Notification API

## Considerations
(1) -(3) should we at some point cache the notification in case sending it through the external service fails? Can we cache on error(?) In that case should probably be an external cache as we are not guaranteed which instance picks up the notification nex time. 
(1) can we assume that all notifications that make their way to the kafka topic have been validated okay, so we can trust all required content is present? 
(3) how many times should we re-try sending an e-mail if it fails? 
(4) Do we need a client library or is the implementation so small we don't mind duplicating it?
(5) Consideration: find out if kafka consumer and producer should be a part of integration or core project

## Tasks
- [x] Implement a consumer for reading an email object from Kafka
- [x] Implement a client to send email from the service (Communication services)
~~- [ ] Implement a logic for checking status for a sent email  and to obtain the final result~~ moved to seperate issue
- [x] Implement logic for triggering the sending of a notification via email to the provided recipient 
- [x] Implement logic for reporting back the status after a email is (attempted) sent (push to topic )
- [x] Unit tests
- [x] QA
- [x] Manual test is complete (if relevant)
- [x] Automated test is implemented (if relevant)
     - Health check will be implemented in separate issue

## Test
- Publish a notification to the kafka topic for a receipient with an invalid/non-existing email ensure correct status is set in database
- Publish a valid notification to the kafka topic, ensure an email is sent and that the correct status is set in the database

Emails
- vg.no
- test@testcom

body
- invalid html

## Acceptance criteria
- [x] A notification in the Kafka topic should result in an e-mail being sent to the provided receipient. 
- [x] If sending of e-mail is successful, expected status in the database is succsessful

Coped out negative tests.
