### ISSUE TITLE
App logic to update notification status based on an event

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-notifications#166]
## Description

When a status is retrieved from Kafka the notification service should update database 

## Tasks
- [x] Implement a consumer for reading a status-message from Kafka
- [x] Implement service for update status in database
- [x] Implement necessary repository-logic
- [x] Unit tests
- [x] QA
- [ ] Manual test is complete (if relevant)
~~- [ ] Automated test is implemented (if relevant)~~ health check will be implemented in separate issue

## Test
- Publish a status to the kafka topic for an notification and ensure correct status is set in database

## Acceptance criteria
- [x] A status-message in the Kafka topic should result in updated database. 
- [x] If update of database fails, the retry mechanism kicks inn

**Comment by acn-sbuad** [comment]
Happy path works well. 
Negative testing is not successful. Introduced an exception in the code to force an error and retry logic / not committing the read of the message. Howver, seems flow stops for this one instance. 

A bit unsure of our implementation of the consumer. If our error handling entails publishing message to a retry topic, we should be fine to commit the initial read.

**Comment by acn-sbuad** [comment]
found an issue and addressed it in #252. 
Closing issue as everything is verified ok
