### ISSUE TITLE
Set up alert for increased number of 500 errors

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#175]
### Description

We want to monitor if our component returns an unexpected increase in 500 response codes to API requests. 
This alert is in place for other platform components and should be present for the notifications component as well.

### Tasks

- [ ] Set up alert in terraform script
- [ ] QA
- [ ] Manual test
- [ ] Deploy to AT
- [ ] Deploy to YT
- [ ] Deploy to TT
- [ ] Deploy to production	

### Acceptance Criterias

- [ ] An alert is pushed to alerts-test if increase of error responses in AT/YT
- [ ] An alert is pushed to alerts-prod if ncrease of error responses in  TT/Prod

**Comment by acn-sbuad** [comment]
Handled by altinn/altinn-platform#418
