### ISSUE TITLE
Implement trigger for internal tasks as k8s CronJob

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#193]
### Description

We need to call an internal endpoint to trigger timed tasks. 
These can be triggered by a kubernetes cron job. 

## Considerations

- How many times should we retry if the cronjob fails? Setting limit of 3 for now. 
- How do we ensure old failed instances are not persisted after we've been notified
### Tasks

- [x] Cron job for pendring orders trigger
- [x] Cron job for send email
- [x] [QA](https://dev.azure.com/brreg/altinn-studio-ops/_git/altinn-studio-ops/pullrequest/700)
- [x] Clean up pipelines and PR related to alternative solution
- [x] Test
- [ ] Documentation

### Acceptance Criterias

- [x] A request is sent to the respective trigger endpoints on the specified schedule
