### ISSUE TITLE
Support for sending of SMS notification to known mobile number

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#201]
### Description

This epic builds on the changes in epic #148 and will be adding mechanisms to support SMS notifications. 

Will support sending an SMS from _Altinn_ to a known mobile number. 
Issues out of scope: 
- #333 

### Workflow: Order placement for SMS notification 

New endpoint for taking an order request an ensuring that the order is stored correctly for processing.

```[tasklist]
#### Tasks
- [ ] https://github.com/Altinn/altinn-notifications/issues/338
- [ ] #336
- [ ] https://github.com/Altinn/altinn-notifications/issues/328
- [ ] https://github.com/Altinn/altinn-notifications/issues/337
- [ ] https://github.com/Altinn/altinn-notifications/issues/339
- [ ] #340
```

### Workflow: Processing past due orders

Job that can pick up orders that have a requested send time that require processing. Splitting an order into notifications.

```[tasklist]
#### Tasks
- [ ] https://github.com/Altinn/altinn-notifications/issues/341
- [ ] https://github.com/Altinn/altinn-notifications/issues/342
- [ ] https://github.com/Altinn/altinn-notifications/issues/343
- [ ] #398
```
### Acceptance criteria
- [x] Sms notification table is populated when sms orders are processed. 

### Workflow: Processing new SMS

Job that can pick up SMS notifications from the database and produce SMS requests to Kafka Topic

```[tasklist]
#### Tasks
- [ ] https://github.com/Altinn/altinn-notifications/issues/353
- [ ] https://github.com/Altinn/altinn-notifications/issues/351
- [ ] https://github.com/Altinn/altinn-notifications/issues/350
- [ ] https://github.com/Altinn/altinn-notifications/issues/399
```

#### Acceptance criteria
- [x] New notifications picked up for sending are marked as "Sending" in database.
- [x] A notification that is processed should result in an sms being sent from Link Mobility

### Workflow: Recording send status and results

Logic that can read from Kafka and pick up the status and/result of an SMS sending in order to handle the result and persisting it to the database

```[tasklist]
#### Tasks
- [ ] https://github.com/Altinn/altinn-notifications/issues/360
- [ ] https://github.com/Altinn/altinn-notifications/issues/361
```

### Workflow: Get order by ID

Expand endpoint to include SMS related details like texts and phone number

```[tasklist]
#### Tasks
- [ ] #331
- [ ] #364
- [ ] https://github.com/Altinn/altinn-notifications/issues/332
```

### Workflow: Get order with status

Expand endpoint to include status for SMS orders.

```[tasklist]
#### Tasks
- [ ] https://github.com/Altinn/altinn-notifications/issues/356
- [ ] https://github.com/Altinn/altinn-notifications/issues/358
- [ ] https://github.com/Altinn/altinn-notifications/issues/373
- [ ] https://github.com/Altinn/altinn-notifications/issues/359
- [ ] https://github.com/Altinn/altinn-notifications/issues/427
```

### Workflow: Get SMS notification summary

Introduce endpoint for reporting status for sms notitifcations related to a single orderorders.

```[tasklist]
#### Tasks
- [ ] #417
- [ ] #415
- [ ] #414
- [x] Altinn/altinn-studio-docs#1399
- [ ] https://github.com/Altinn/altinn-notifications/issues/428
```

### Project setup  & CI/CD

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-notifications/issues/335
```

### Workflow: Send SMS @tba76 

Triggered by new messages on a Kafka Topic. Send SMS

```[tasklist]
#### Tasks
- [ ] https://github.com/Altinn/altinn-notifications/issues/362
- [ ] https://github.com/Altinn/altinn-notifications/issues/368
- [ ] https://github.com/Altinn/altinn-notifications/issues/366
- [ ] https://github.com/Altinn/altinn-notifications/issues/367
- [x] Documentation: architecture
```

### Workflow: Report back the result of sending SMS

Report back the result of to the central application through a Kafka topic.

```[tasklist]
#### Tasks
- [ ] https://github.com/Altinn/altinn-notifications/issues/369
- [ ] https://github.com/Altinn/altinn-notifications/issues/374
```

### Workflow: Handle the callback calls with the delivery report from SMS provider 

A part of the API is a callback from the SMS provider with a delivery report. This must be handled and reported back to the central application for storage.

```[tasklist]
#### Tasks
- [ ] https://github.com/Altinn/altinn-notifications/issues/377
- [ ] https://github.com/Altinn/altinn-notifications/issues/376
- [ ] https://github.com/Altinn/altinn-notifications/issues/378
- [ ] https://github.com/Altinn/altinn-notifications/issues/426
```

**Comment by acn-sbuad** [comment]
All related issues closed a while ago. Closing epic
