### ISSUE TITLE
Support for lookup of email address and mobile number for given person or organisation

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#203]
## Description
The Notification component should be able to identify an email address and/or mobile number when the intended recipient of a notification is a person or organization. 

1. The profile lookup should occur at the time when the notification is to be sent. 
2. There should also be a lookup with the placement of the order in order to give feedback about the likely outcome.
3. It should be unnecessary to do a lookup if the notification already have a target with an address.
4. The lookup is done only if the Notification.PartyReference is filled in with an (SSN - National Identity Number) or organization number.

Other issues will cover lookup based on other values and properties like InstanceId.

## Workflows
The work is split into workflows. Completing a single workflow should add new value or introduce a new feature in Altinn Notifications.  The workflows are placed in the order of development and functionality that is reused by a later workflow only needs to be specified once by the workflow that first implements the functionality. 

### Send notification to person identified with national identity number 

**Altinn's responsibility:** 
- Lookup contact point in Altinn's copy of KRR.
- Consider reservation in KRR
  - Recipient has no reservations => send notification
  - Recipient has reservation & app owner has bypassed => send notifications
  - Recipient has reservation & app owner has NOT bypassed => return error message to application owner

**App owner responsibility:** 
- Provide national identity number of recipient
- State whether sending notification should bypass reservations in KRR

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-notifications/issues/436
- [ ] https://github.com/Altinn/altinn-profile/issues/132
- [ ] https://github.com/Altinn/altinn-profile/issues/136
- [ ] https://github.com/Altinn/altinn-notifications/issues/446
- [ ] https://github.com/Altinn/altinn-notifications/issues/437
- [ ] https://github.com/Altinn/altinn-notifications/issues/439
- [ ] https://github.com/Altinn/altinn-notifications/issues/441
- [ ] https://github.com/Altinn/altinn-notifications/issues/496
- [ ] https://github.com/Altinn/altinn-studio-docs/pull/1546
```

### Support notification to organization by organization number _without_ service affiliation
**Altinn's responsibility:** 
- Lookup organization contact point in Altinn's copy of KoFuVi 
~~- Lookup user contact point in Altinn Profil (din kontaktinformasjon for virksomhet)~~
    
**App owner responsibility:** 
- Provide organization number of recipient

#### Requirements
- Fall back to main unit if sub unit doesn't have contact information
- Separate endpoints for official and personal contact information on the organization
- Make it possible to filter contact information based on any resource registered in resource registry.

#### Questions
__Authorization of access to the resource that the notification is about__
- What if different people have read access to different steps in the process?
- How to handle those cases?
- Do we need to?
- What if the policy have completely different actions? (Not `read`)

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-notifications/issues/442
- [ ] https://github.com/Altinn/altinn-notifications/issues/455
- [x] Dependency on issue #436
- [x] Dependency on issue #446
- [ ] https://github.com/Altinn/altinn-notifications/issues/450
- [ ] https://github.com/Altinn/altinn-notifications/issues/456
- [ ] https://github.com/Altinn/altinn-notifications/issues/507
- [ ] https://github.com/Altinn/altinn-notifications/issues/511
- [ ] Add functionality to localtest https://github.com/Altinn/altinn-notifications/issues/496
```

### Workflow: Support notification to organization by organization number _with_ service affiliation
**Altinn's responsibility:** 
- Lookup organization contact point in Altinn's copy of KoFuVi 
- Lookup user contact point in Altinn Profil (din kontaktinformasjon for virksomhet)
  - contact point is only retrieved for user's that satisfy the following: 
    - User can represent the organization
    - User has registered a personal contact point for the organization in Altinn
    - User has access to the affiliated service through a role, access group or direct delegation
    - User has no limitations on which services it should be notified about OR user has whitelisted notifications related to the affiliated service
    
**App owner responsibility:** 
- Provide organization number of recipient
- Provide resourceId for affiliated service 

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-notifications/issues/470
- [ ] https://github.com/Altinn/altinn-notifications/issues/449
- [ ] https://github.com/Altinn/altinn-notifications/issues/504
- [ ] #451
- [ ] #472
- [ ] https://github.com/Altinn/altinn-notifications/issues/508
- [ ] https://github.com/Altinn/altinn-notifications/issues/510
- [ ] https://github.com/Altinn/altinn-notifications/issues/512
- [x] Do we send notifications to the official contact address if there is a service affiliation with role requirements? YES
```

### Workflow: Support notification to person identified by national identity number _with_ service affiliation

**Altinn's responsibility:** 
Altinn will generate notifications to a person ragardless of resource affiliation. There are currently no feature in Altinn to send notifications to somone else when the recipient of a notification is a person.
- Consider reservation in KRR for each recipient
  - Recipient has no reservations => send notification
  - Recipient has reservation & app owner has bypassed => send notifications
  - Recipient has reservation & app owner has NOT bypassed => return error message to application owner

**App owner responsibility:** 
- Provide national identity number of recipient
- Provide appId for affiliated service 
- State whether or not notification should bypass reservations in KRR

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-notifications/issues/524
```

**Comment by acn-sbuad** [comment]
All related issues closed. Closing epic.
