### ISSUE TITLE
Upgrade PostgreSQL to version 15/16

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#238]
### Description

Version 16 of PostgreSQL has now been released and we should consider upgrading our servers.

https://www.postgresql.org/about/news/postgresql-16-released-2715/

### Additional Information

Postgresql version 16 is not available in Azure yet.
Currently the servers are on version 14, they should be upgraded to version 15 for now instead.

### Tasks

- [x] Updated Terraform script for NotificationsDB
- [x] Investigate / fix issue with adminuser rights after upgrade
- [x] Updated Notifications-db in AT21
- [x] Updated Notifications-db in AT22
- [x] Updated Notifications-db in AT23
- [x] Updated Notifications-db in AT24
- [x] Updated Notifications-db in YT01
- [x] Updated Notifications-db in TT02
- [x] Updated Notifications-db in PROD

### Acceptance Criterias
- [x] Clean db deploy is successful
- [x] Use case tests still run green

**Comment by acn-sbuad** [comment]
Verified ok in AT
