### ISSUE TITLE
Update LocalTest with the notification features introduced for sending email

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#239]
### Description

Update LocalTest to include the new notification endpoints. The goal is to support an app that would want to trigger the sending of email. First version of this should not be able to produce an actually email. It's enough that it results in a file stored to disc.

### Additional Information

Only the POST endpoint for creating an order is assumed to be needed for now.

### Tasks

- [x] Copy necessary controllers from Notification to LocalTest
- [x] Write necessary services to ensure that a file with the original notification order as content

### Acceptance Criterias

- [ ] The email notification order produced by an app is stored to disc as a json file.

**Comment by acn-sbuad** [comment]
leaving testing up to team apps when functionality is required. Initial resting has been conducted locally
