### ISSUE TITLE
Update KafkaProducer to return false instead of throwing an exception. Create alert rules to detect cases

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#245]
## Description
Currently Producer exceptions are thrown to the service calling the producer.
As the service cannot do anything with e.g. a non existing topic, so it should rather return false and log the exception. 

We should have alert rules to monitor exceptions of this type in Azure. 

## Tasks
- [x] Update producer logic in notifications and notifications email
- [x] Add alert rule to terraform rule set
- [x] QA
- [x] QA alert rules: https://dev.azure.com/brreg/altinn-studio-ops/_git/altinn-studio-ops/pullrequest/731
- [x] Test 

## Test
- [x] adjust topic name in env variables, restart pods and run use case tests

## Acceptance criteria
- [x] In case of exceptions an alert should be sent to slack

**Comment by acn-sbuad** [comment]
Manual set up alert verified in at22. will be rolled out with next aks update
