### ISSUE TITLE
Make from address optional, use default noreply@altinn.cloud/no

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#246]
## Description 
From address should be optional to provide

## Tasks
- [x] Change validation and implementation
- [x] QA
- [x] Manual test

## Acceptance critria
- [x] It is possible to send an email order without providing from address
- [x] noreply altinn address is the sender if nothing else is provided by the entity ordering a notificiation
