### ISSUE TITLE
Create order should return an object serialized to JSON

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#247]
## Description
Currently the order id is returned as a string from the post endpoint. 
It should be returned as a json object. 

## Tasks
- [x] Create return model
- [x] Update controller ouput
- [x] Update tests
- [x] QA
- [x] Update APIM swaggr and docs

## Acceptance criteria
- [x] Return object from orders POST should be a json object

**Comment by acn-sbuad** [comment]
Verified return object

```
{
    "orderId": "7898e81a-db9f-4d76-9ec9-c25fa8b4a132"
}
```
