### ISSUE TITLE
Register scopes and delegation schemes to access notifications

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#265]
### Description
We need to create delegation schemes that makes it possible for an application owner to delegate the necessary scopes to a provider/supplier. We also need to give the scopes to the application owners.

### Additional information
We already have some scripts that can do what we need in the [MaskinportenTokenGenerator repository](https://github.com/Altinn/MaskinportenTokenGenerator/tree/master/scripts).

#### Existing documentation
- How to set up a new client in Maskinporten needed for tooling. 
    https://docs.altinn.studio//technology/solutions/cli/configuration/maskinporten-setup/
- Delegation scheme delegation.
    https://docs.altinn.studio//api/authentication/delegate-scopes/
- Administration of delegation schemes in Altinn. These are used by Maskinporten to determine access for contractors
    https://altinn.github.io/docs/utviklingsguider/api-delegering/api-eier/

```[tasklist]
### Tasks
- [x] Create a tool that can give all application owners the necessary scopes
- [x] Expand the tool to give scopes to a new application owner (all/selected scopes)
- [x] Create the altinn:serviceowner/notifications.create scope in maskinporten - TEST
- [x] Create the altinn:serviceowner/notifications.create scope in maskinporten - Production
- [x] Ensure that all existing application owners get scope altinn:serviceowner/notifications.create - TEST
- [x] Ensure that all existing application owners get scope altinn:serviceowner/notifications.create - Production
- [x] Create delegation schemes with a policy for the scope - TEST
- [x] Create delegation schemes with a policy for the scope - Production
- [x] Documentation of scope administration with the powershell scripts
```

The tooling being referred to in the first task ended up being the PowerShell scripts in the MaskinportenTokenGenerator repository. There is a solid set of commands and options that can be used in administration of scope access.
