### ISSUE TITLE
Use case testing in production. Authentication as an ORG.

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#266]
## Description
We need a way for us to trigger activity in Notifications in order to detect possible issues with the service.

Use Azure DevOps pipline if that is easier than using github actions.

Creating maskinporten client: 
KID: follow same pattern as for events
Scopes: altinn:serviceowner/notifications:create

Follow doc: [docs.altinn.studio/technology/solutions/cli/configuration/maskinporten-setup](https://docs.altinn.studio/technology/solutions/cli/configuration/maskinporten-setup/)
base64 encoded jwk should be added as an action secret to the repository.

### Task
- [x] Find a way for us to act as an application owner in production.
- [x] Add maskinporten support to k6 test project
- [x] Set up workflow for TT & prod
- [x] Create maskinporten integration for test and prod 
- [x] Add maskinporten values to action secrecrets in repo
