### ISSUE TITLE
Set up event grid and webhook to receive updates for operations

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#281]
### Description 
https://learn.microsoft.com/en-us/azure/event-grid/communication-services-email-events

DR endpoint must be able to 
(1) verify itself towards event grid 
(2) receive and further report status of an email 

Documentation on endpoint validation: https://learn.microsoft.com/en-us/azure/event-grid/webhook-event-delivery#validation-details

### Task

- [x] Implement DR endpoint i Email
- [x] Update APIM
- [x] Add accesskey to terraform
- [x] Add new result types to DB
- [x] Add descriptions for new result types in core
- [x] Update docs to reflect new result types
