### ISSUE TITLE
Dokumentering av arkitektur o.l. overordnet

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#282]
PR altinn/altinn-studio-docs#1361

Existing doc: https://www.altinndigital.no/produkter/varsling/
https://altinn.github.io/docs/utviklingsguider/varsling/

## Tasks

- [API ](https://docs.altinn.studio/notifications/api/)
  - [ ] ID-porten Guides
  - [ ] Altinn token guides 
  - [x] Maskinporten guides
  - [x] OpenAPI
- [x] Architecture
  - [x] [Notifications](https://docs.altinn.studio/notifications/architecture/notifications)
  - [x] [Notifications Email](https://docs.altinn.studio/notifications/architecture/email) 
  - [x] [Kafka](https://docs.altinn.studio/notifications/architecture/kafka/)
- [ ] [Send notifications](https://docs.altinn.studio/notifications/send-notifications/)
  - [ ] Get Started
    - [ ] [User guide](https://docs.altinn.studio/notifications/send-notifications/get-started/)
    - [x] Maskinporten guide
  - [x] Developer guides

**Comment by annerisbakk** [comment]
[](https://github.com/Altinn/altinn-notifications/issues/394)
[](https://github.com/Altinn/altinn-notifications/issues/395)
[](https://github.com/Altinn/altinn-notifications/issues/396)

**Comment by acn-sbuad** [comment]
Closing. Issues have been generated for remaining work
