### ISSUE TITLE
Document the Kafka infrastructure

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#283]
### Description

Update infrastructure documentation to include description and explanation of the Kafka service setup.

### Additional Information

Document on Altinn pedia. https://pedia.altinn.cloud

### Tasks

- [x] Document differences between environments
- [x] Document the reason for why everything is connected to our production subscription
- [x] Document networks and network peering 
- [x] Document anything that can be of help to anyone that needs to work on the code in the future

**Comment by simon-ellefsen** [comment]
https://pedia.altinn.cloud/altinn-3/infrastructure/environments/kafka/
