### ISSUE TITLE
Review domain models

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#295]
## Description
Found a few minor issues in the external models to fix

## Tasks
- [x] Serialize ContentType as "contentType" instead of "content-type".
- [x] Make an external version of NotiricationChannel.
- [x] Non nullable Subject and Body in EmailTemplateExt

**Comment by acn-sbuad** [comment]
Regression test successful
