### ISSUE TITLE
Extend API logic for getting order by id 

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#331]
## Description 
When adding support for an additional communication channel the order object presented to the end user should also reflect all communication channels. 

## Consideration
- Could we add handlers for each template mapper for instance, so there is no need for larger changes in the main mapper class? e.g. Command Pattern 

## Tasks
- [x] Extend NotificationOrderExt with sms template properties 
- [x] Extend OrderMapper with a case for handling the SMS template in `MapToNotificationOrderExt`
- [x] Implement unit tests
- [x] QA
- [x] Manual test of orders/{id}
- [x] Manual test of orders?sendersRef={sendersRef}

## Acceptance criteria

**Comment by acn-sbuad** [comment]
Tested in AT22. 

Response 

```json
{
  "id": "400788eb-f9ab-4872-9cdb-1ea1358bfd46",
  "creator": "ttd",
  "requestedSendTime": "2024-02-02T12:43:15.8656387Z",
  "created": "2024-02-02T12:43:15.9432741Z",
  "notificationChannel": 1,
  "recipients": [
    {
      "mobileNumber": "++4799999999"
    }
  ],
  "smsTemplate": {
    "senderNumber": "",
    "body": "A message sent from an application owner through Altinn, to be sent immediatley."
  },
  "links": {
    "self": "https://platform.at22.altinn.cloud/notifications/api/v1/orders/400788eb-f9ab-4872-9cdb-1ea1358bfd46",
    "status": "https://platform.at22.altinn.cloud/notifications/api/v1/orders/400788eb-f9ab-4872-9cdb-1ea1358bfd46/status",
    "notifications": "https://platform.at22.altinn.cloud/notifications/api/v1/orders/400788eb-f9ab-4872-9cdb-1ea1358bfd46/notifications"
  }
}
```

Issues: notifications endspoint in links is not implemented. Should be removed. notificationChannel is serialized as an int not string.

**Comment by acn-sbuad** [comment]
both issues adressewd in #412

**Comment by acn-sbuad** [comment]
After fix for sender number:

```json
{
    "id": "1230a3f2-7d2c-40ee-9c64-3b57167dc949",
    "creator": "ttd",
    "requestedSendTime": "2024-02-05T13:41:01.2913648Z",
    "created": "2024-02-05T13:41:01.3951422Z",
    "notificationChannel": "Sms",
    "recipients": [
        {
            "mobileNumber": "+47...."
        }
    ],
    "smsTemplate": {
        "senderNumber": "Altinn",
        "body": "Manuell testing."
    },
    "links": {
        "self": "https://platform.at22.altinn.cloud/notifications/api/v1/orders/1230a3f2-7d2c-40ee-9c64-3b57167dc949",
        "status": "https://platform.at22.altinn.cloud/notifications/api/v1/orders/1230a3f2-7d2c-40ee-9c64-3b57167dc949/status"
    }
}
```
