### ISSUE TITLE
Core logic for placing an sms notification order

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#336]
### Description

Workflow: order placement for SMS notifications will need modifications to the Core layer of the notification app that can support the new endpoint. 

### Tasks
- [x] Extend` NotificationOrder.cs` with required properties to represent an SMS template
- [x] Extend `NotificationOrderRequest.cs` with required properties to represent an SMS template
- [x] Rename `EmailNotificationOrderService` and `IEmailNotificationOrderService`  to `OrderRequestService` and `IOrderRequestService`
- [x] Rename `RegisterEmailNotificationOrder` in `OrderRequestService`  to `RegisterNotificationorder`
- [x] Extend SetFromAddressIfNotDefined in OrderRequestService with logic for setting default SMS sender
- [x] Implement unit tests
- [x] QA
~- [ ] Manual test~ Manual testing not possible as no external endpoints are available

### Acceptance Criterias
- [x] Required intefaces are defined and ready to use by API layer
- [x] Required intefaces are defined and ready to use by persistence layer
- [x] Domain models for `NotificationOrder` and `NotificationOrderRequest` have properties to represent SMS notification templates

**Comment by acn-sbuad** [comment]
Regressoin tests ok. If any future issues occur, these will be handled in relation to other /new issues
