### ISSUE TITLE
Repository logic for placing a SMS notifications order

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#337]
### Description

Workflow: order placement for SMS notifications will need modifications to the persistence layer of the notification app that can support the new endpoint. 

### Consideration
Split into smaller repository classes. GetOrderRepository, CreateOrderRepository, UpdateOrderRepository (?) 

### Tasks
- [x] Define SMS texts table
- [x] Create migration scripts for setting up SMS texts table
- [x] Add logic for retrieving SMS template in `ExtractTemplates` in `OrderRepository.cs`
- [x] Implement function for inserting sms texts 
- [x] Implement logic for calling new function when required
- [x] Change task handling to insert sms and email in parallel and waiting for both tasks at the end
- [x] Implement unit tests
- [x] Implement integration tests
- [x] QA
- [x] Manual testing (if API endpoint is available)

### Acceptance Criterias
- [x] An SMS texts table exists in the database
- [x] Once an order is placed the order including sms template is persisted in the jsonb
- [x] Once an order is places the sms text is persisted in the SMS texts table
