### ISSUE TITLE
Document workflow: Order placement for SMS notification

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#340]
### Description

Write documentation guiding end users in how to place an SMS notification and technical documentation supporting developers that will work with the solution. 

### Tasks
Section: Notifications - Send Notifications - Developer Guides
- [x] Write new section Send sms notifications 

Section: Notifications - Architecture
- [x] Add the new controller to the list over _Public APIs_ in `Notifications - API - Public APIs`
- [x] Consider altering description of trigger controller in `Notifications - API - Internal APIs`
- [x] Update the solution drawing including SMS endpoint to the Notifications API

### Acceptance Criterias
- [x] User documentation enabling end users to send a notification order request for sms notification is in place
- [x] Technical documentation includes an overview of new functionality added to suport workflow: order placement for SMS notification.
