### ISSUE TITLE
Repository logic for placing a sms notification

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-notifications#341]
### Description

Workflow: Notification placement for SMS will need modifications to the persistence layer of the notification app that can support storing of SMS notifications 

### Tasks
- [x] Define SMS Notifications table (wich columns do we need?)
- [x] Create migration scripts for setting up SMS notifications table
- [x] Implement function for inserting SMS notifications 
- [x] Implement logic for calling new function when required
        -create SmsNotification class, use as input
- [x] Implement unit tests
- [x] Implement integration tests
- [x] QA
- [x] Manual testing

### Acceptance Criterias
- [x] New table and function exists
- [x] Once an order with sms-notificatiosn is processed, the sms-notification table should be populated

**Comment by acn-sbuad** [comment]
Test will be completed once remaining workflow is completed
