### ISSUE TITLE
Service logic for placing a sms notification

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-notifications#342]
### Description

Workflow: Notification placement for SMS will need modifications to the core layer of the notification app that can support storing of SMS notifications

### Tasks
- [x] Create new service, SmsNotificationService
- [x] Add new method CreateNotification
    -extract SmsAddressPoint (class must be created it not exists)
    -create new SmsNotification
    -call repository to save new notification
- [x] Implement unit tests
- [x] QA
- [x] Manual test ?

### Acceptance Criterias
- [x] Required intefaces are defined and ready to use by OrderProcessingService
