### ISSUE TITLE
Update OrderProcessingService to handle SMS notification-channel

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-notifications#343]
### Description

Workflow: Notification placement for SMS will need modifications to the core layer of the notification app that can support processing of SMS notifications

### Tasks
- [x] Inject new SmsNotificationService
- [x] Update ProcessOrder method to handle sms-channel. Call correct method on SmsNotificationService.
- [x] Implement unit tests
- [x] QA
- [x] Manual test ?

### Acceptance Criterias
- [x] Orders with sms-channel defined should create sms-notifications in database 
- [x] Retry logic is in place if order processing fails before all notifications are created
