### ISSUE TITLE
New trigger endpoint to start processing SMS notifications

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#350]
## Description
Expand the TriggerController with a new POST endpoint that will start the "Send SMS notifications" process.

## Tasks
- [x] Add a new "sendsms" endpoint to TriggerController
- [x] Have the method call SmsNotificationService.SendNotifications and return Ok().
- [x] Ensure that the endpoint is ignored by API Explorer
- [x] Implement cron job for calling endpoint
- [x] Documentation
- [x] Review/QA
- [x] Manual testing

## Acceptance Criteria
- [x] The endpoint responds with 200 OK
- [x] The endpoint is hidden from the generated OpenAPI spesification.
