### ISSUE TITLE
New core service called SmsNotificationsService handling Business logic for SMS

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#351]
## Description
Create a new service that can handle SMS notification specific logic. Add logic to retrieve unsent SMS notification and have them sent.

## Tasks
- [x] Create interface and service class
- [x] Add method to be called from SMS sending trigger
    - Retrieve unsent SMS notifications
    - Loop through SMS notifications and "send them"
    - Update send status for each
~~- [ ] Documentation~~ nothing new to document
- [x] Review/QA
- [x] Manual testing

## Acceptance Criteria
- [x] The result of calling the method is that no SMS notifications have status "new"

**Comment by acn-sbuad** [comment]
verified in at22
