### ISSUE TITLE
Add necessary repository logic to start sending of new SMS notifications.

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#353]
## Description
Update Repository logic and PostgreSQL objects to support sending of SMS notifications.

## Tasks
- [x] Create a new function called `getsms_statusnew_updatestatus`. The function should retrieve all new SMS notifications and update them with a status indicating that they are being processed. Status "Sending". Use `getemails_statusnew_updatestatus` as inspiration.
- [x] Update the SmsNotificationRepository class with a method; `GetNewNotifications` to retrieve SMS notifications with the new function. Create the Repository class if not already added by another change.
- [x] Write integration tests
~~- [ ] Write unit tests~~
- [x] Review
- [ ] Documentation

## Acceptance criteria
- [ ] Method returns all SMS notifications not already processed for "Sending". 
- [ ] When the method has returned all SMS notifications are marked as "Sending".

**Comment by acn-sbuad** [comment]
Will be tested once full workflow is implemented
