### ISSUE TITLE
Kafka producer to write new SMS orders to topic

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#354]
## Description
Add logic to store new SMS notifications to a Kafka topic.

## Tasks
- [ ] Write a new KafkaProducer that can take an SMS notification and write the content to correct topic.
- [ ] Write integration tests
- [ ] Write unit tests
- [ ] Perform review
- [ ] Update erlevant documentation

## Acceptance criteria
- [ ] Given SMS notifications are written to correct Kafka topic.

**Comment by acn-sbuad** [comment]
Generic kafka producer implemented. So closing this issue.
