### ISSUE TITLE
Changes needed for the orders status API (`/orders/{id}/status`)

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#356]
## Description
Here we are extending `GetWithStatusById` method of `OrdersController` to get the status of an order by ID with SMS details beside already existing email.

Controller Name: `OrdersController`
Endpoint: `GET notfications/api/v1/orders/{id}/status`

## Consideration
The value of `notificationChannel` in the output JSON currently is a string which may need to changed to an object or array when this SMS notification channel will be introduced. Complication can be arose when changing this from string to object or array which need to be discussed.

## Tasks
- [x] Need to extend `NotificationStatusSummaryExt.cs` by adding another JSON property for SMS.
- [x] Need to extend the `MapToNotificationOrderWithStatusExt` method from `OrderMapper.cs` file to adapt it for the SMS notification(See the `switch` statement the `foreach` loop). 
- [x] Need to add another member to the `NotificationChannelExt` enum datatype.
- [x] QA
- [x] Test
## Acceptance Criteria
When getting called this API should return another group of values for SMS under `notificationsStatusSummary` which should be be marked by the key `sms`.

Example:
```json
{
  "id": "string",
  "sendersReference": "string",
  "requestedSendTime": "2024-01-09T14:22:34.559Z",
  "creator": "string",
  "created": "2024-01-09T14:22:34.559Z",
  "notificationChannel": "Email",
  "processingStatus": {
    "status": "string",
    "description": "string",
    "lastUpdate": "2024-01-09T14:22:34.559Z"
  },
  "notificationsStatusSummary": {
    "email": {
      "links": {
        "self": "string"
      },
      "generated": 0,
      "succeeded": 0
    },
    "sms": {
      ...
    }
  }
}
```

**Comment by acn-sbuad** [comment]
Verified in AT22

```json
    "notificationsStatusSummary": {
        "sms": {
            "links": {
                "self": "https://platform.at22.altinn.cloud/notifications/api/v1/orders/5168f884-06e5-43b4-bbf1-3b7efcc7b62a/notifications/sms"
            },
            "generated": 1,
            "succeeded": 0
        }
    }
```
