### ISSUE TITLE
Repository changes needed for getting order with status (API: `/orders/{id}/status`)

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#358]
## Description
This issue lists the tasks needed to be done for the changes for the repository layer regarding issue #356 .

## Tasks
- [x] Extend `getorder_includestatus` SQL function to get the `generatedSmsCount` and `succeededSmsCount`. SQL function located at `src/Altinn.Notifications.Persistence/Migration/v0.09/02-setup-functions.sql`. Note that a new directory needed to be created with proper version number(i.e. `v0.15`) if it's not already there and a new file need to be created with proper naming convention like other `*.sql` file. Then modified function need to be put there and change the relevent occurrence in the C# code.
- [x] Extend `GetOrderWithStatusById` method in the `OrderRepository.cs` file. (Hint: the `while` loop body)
- [x] Extend `NotificationTemplateType` enum by adding another member name `Sms` for the SMS notification.
- [x] QA
- [x] Regression test email 
## Acceptance Criteria
From the *Acceptance Criteria* of issue #356 the content of the `sms` part in the JSON value, will be populated from this changes.
