### ISSUE TITLE
Implement consumer for reading a status-message from Kafka

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-notifications#360]
### Description

Workflow: Update status for an SMS notifications will need modifications to the integrations/service layer of the notification app. 

### Tasks
- [x]  Implement a consumer for reading an sms-status object from Kafka
- [x] Implement service (if not implemented) to call procedure for update status in db
- [x] Call service from consumer
- [x] Implement unit tests
- [x] Implement integration tests
- [x] QA
- [x] Manual testing (if API endpoint is available)

### Acceptance Criterias
- [x] Once an sms status message is received from Kafka,  status is persisted in db
