### ISSUE TITLE
 Set up access to SMS service at Link Mobility

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#362]
## Description 
Link mobility will be used for sending SMS. 
We need to set up access to both test and production environment 
and store required connection secrets in key vault.

## Tasks
- [x] Research ways to connect to service
- [x] Set up logic or practice for storing required secrets in KV
~~- [ ] Investigate setup for the callback webhook~~
- [x] Document setup process. Not a lot to document. A notis made in OneNote
- [x] Manual verification

### Success response
```json
{
	"GatewayReference": "8c6a6738-ca73-4758-9330-d0bbd124a1d6",
	"IsStatusOk": true,
	"StatusText": "",
	"Message": {
		"SenderNumber": "Altinn",
		"ReceiverNumber": "+47(...)",
		"Text": "Hello, World!",
		"IsFlashMessage": false,
		"Replace": null,
		"Payment": null,
		"TimeToLive": null,
		"DeliveryTime": null,
		"Type": null
	}
}
```

- ReceiverNumber must be with country code. min 9 chars. + og 00, both are accepted. 

### Error response
```json
{
	"GatewayReference": null,
	"IsStatusOk": false,
	"StatusText": "Invalid RCV '(...)'. Receiver number must be at least 9 digits.",
	"Message": {
		"SenderNumber": "Altinn",
		"ReceiverNumber": "(...)",
		"Text": "Hello, World!",
		"IsFlashMessage": false,
		"Replace": null,
		"Payment": null,
		"TimeToLive": null,
		"DeliveryTime": null,
		"Type": null
	}
}
```

## Acceptance Criteria
- [x] SMS micro serivce in AT, TT, YT has access to secrets enabling it to connect to the Link Mobility API (test env)
- [ ] SMS micro serivce in production has access to secrets enabling it to connect to the Link Mobility API (prod env)

**Comment by acn-sbuad** [comment]
Tried accessing using LinkMobility's SDK, but endpoint is hard coded. 
Have followed up with an issue in their repository: 
https://github.com/PSWinCom/LinkMobility.PSWin.Client/issues/3
