### ISSUE TITLE
Implement consumer for reading sms-message objects from Kafka

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-notifications#366]
### Description

Workflow: Send SMS will need modifications to the integration layer of the notification-sms app. 

### Consideration
- [x] How should we handle retries/exceptions?

### Tasks
- [x]  Implement a consumer for reading an sms-message object from Kafka (defined in altinn-notification)
- [x] Call service from consumer
- [x] Implement unit tests
- [x] Implement integration tests
- [x] QA
- [x] Manual testing (if API endpoint is available)

### Acceptance Criterias
- [x] Once an sms message is received from Kafka,  sms will be sent to sms-gateway
