### ISSUE TITLE
Implement a client to send sms messages (Link Mobility)

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-notifications#367]
### Description

Workflow: Send SMS will need modifications to the integrationlayer of the notification-sms app. 

### Consideration
Different behaviour for error-messages?
https://wiki.pswin.com/Verify-that-message-has-been-sent.ashx

### Tasks
- [x]  Implement a client that can send new messages to Link Mobility (use client from Link, https://github.com/PSWinCom/LinkMobility.PSWin.Client)
- [x] Implement integration tests
- [x] QA

### Acceptance Criterias
- [x] A client for communication with Link Mobility api exists. The client must have method for send sms.
