### ISSUE TITLE
Create a kafka client to write messages to a kafka topic

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#369]
### Description
Write the necessary logic to write messages to any Kafka topic. This issue assume that no other issue/tasks have done this before. The implementation can probably be copied from the CommonProducer in the email code.

### Tasks
- [x] Create a CommonProducer identical to the CommonProducer in altinn-notifications-email solution.
- [x] Implement unit tests
- [x] Implement integration tests
- [x] QA
- [x] Manual testing (if API endpoint is available)

### Acceptance criteria
- [x] Serialized messages given to the producer together with a topic name is written to the topic.
