### ISSUE TITLE
Update SMS Service logic to report the result of sending an SMS

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#374]
### Description
Make necessary core service adjustments to support SMS notification status updates.

Topic name: `altinn.notifications.sms.status.updated`

### Analysis
The existing StatusService class is bound to Email through its dependency to EmailServiceClient.
The existing SendOperationStatus is bound to Email through its dependency to EmailSendResult.

### Tasks
- [x] Create a new SendOperationStatus class for SMS sending status/results.
- [ ] Create a new StatusService class for SMS status logic.
- [ ] Implement an UpdateSendStatus method that handle SMS send status messages. Have it call a KafkaProducer to write given status to a Kafka topic.
- [x] Update existing SMS Sending logic to call UpdateSendStatus with the resulting status.
- [x] Implement unit tests
- [x] Implement integration tests
- [x] QA
- [x] Manual testing (if API endpoint is available)

### Acceptance criteria
- [x] The result after sending an SMS is stored to correct Kafka topic.
