### ISSUE TITLE
Implement core logic for sms notification summary

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#415]
### Description

Sms notification summary should be made available for end users through the API and depict the status of the individual notifications generated by an order

### Tasks

- [x] Implementation 
- [x] QA
- [x] Regression tests

### Acceptance Criterias

- [x] Interfaces are defined for persistence to implement
- [x] Models related to sms summary are defined
- [x] Interface and implementation of services are made available to API layer
