### ISSUE TITLE
Implement API logic for sms notification summary

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#417]
### Description

Sms notification summary should be made available for end users through the API and depict the status of the individual notifications generated by an order

Endpoint /orders/{orderId}/notifications/sms

### Tasks

- [x] Implement required mappers and external models
- [x] Implement endpoint
- [x] Implement tests
- [x] QA
- [x] Manual testing 

### Acceptance Criterias

- [x] An end user can only get an sms notification summary of a notification they are the creator of (e.g. org can only requests notifications for their own org)
- [x] Notifications scope or platform access token is required to access the API. 403 response if missing.
- [x] Response code is 200 if notification summary is returned
- [x] Response code is 404 if end user is not authorized to see notfications for the given order id or if order id does not exist 
- [x] All result types have English natural language descriptions in the response

**Comment by acn-sbuad** [comment]
Verified in at23
