### ISSUE TITLE
Extend notification order with service affiliation

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#435]
### Description

A notification order may or may not have a service affiliation identified by a resource id and (optionally) a resource instance. 

An organization should be able to link a notification order request to a resource. The properties should be persisted in the database and made available when recipients are to be identified. 

### Considerations

- Should it be required to provide the person or organization number for the recipient if a resource id is provided? 
  - Yes, it should not be up to Notifications to identify the instanceOwner's person or organization number based of the resource id. Use cases for this will be that an order is placed from an app or a system that has access to the instance data, from which the person or organization number is easily available. 
  
- Should the resource affiliation properties be exposed in the notifications summaries (e.g. notifications/api/v1/orders/{orderId}/notifications/email) and order status endpoint? 
  - No, resource affiliation should be treated as a part of the notification templates and not be included in OrderWithStatus or NotificationSummary model. This saves us from having to retrieve data from the jsonb or placing the data in individual columns to support retrieval in relation to notification summaries. 

### Assumptions / Pre-requisites
- [x] Flag for bypassing reservation in KRR is defined on the notification order object

### Tasks

- [x] Add resource affiliation properties to external order models
    - EmailNotificationOrderRequestExt
    - SmsNotificationOrderRequestExt
    - NotificationOrderExt
- [x] Add resource affiliation properties to domain models
    - NotificationOrderRequest
    - NotificationOrder
- [x] Add mapping of service affiliation to relevant mapper methods in OrderMapper.cs
- [x] Add / extend unit tests
- [x] QA
- [x] Manual testing

### Acceptance Criterias

- [x] It is possible to place an email notification order with a service affiliation
- [x] It is possible to place an SMS notification order with a service affiliation
- [x] The service affiliation of a notification order is persisted in the database
- [x] The service affiliation of a notification order is exposed to the end user through all GET endpoints for an order
- [x] Posting an order with a service affiliation missing application id results in a 400 response
- [ ] Posting an order with a service affiliation missing instance id results in a 202 accepted response.
- [x] Regression tests are successful

**Comment by acn-sbuad** [comment]
Implemented in #511. No support for adding instanceId yet. Will be a new feature if ever required
