### ISSUE TITLE
Add national identity number to Recipient model

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#436]
## Description 
A notification order may be sent to a person only identified by their national identity number

Out of scope: Accepting only a national identity number in the order request. 

## Consideration
- [x] What term should we use for a person number / national identity number? 
  - Discussion will be raised on Slack to get a consensus across the platform solutions before deciding. 
  - NationalIdentityNumber
- [ ] A base class for all recipient types? 

## Tasks
__API__
- [x] Add national identity number and organization number properties to external recipient model, RecipientExt
- [x] Add mapping of recipient national identity number and organization number to relevant mapper methods in OrderMapper.cs
- [x] Add mapping of new properties in both NotificationSummaryMappers

__Core__
- [x] Modify Recipient.cs
  - Add national identity number property
  - Add organization number property
  - Remove recipient id poroperty
- [x] Modify EmailRecipient.cs
  - Add national identity number property
  - Add organization number property
  - Remove recipient id poroperty
- [x] Add SmsRecipient.cs
  - Add national identity number property
  - Add organization number property
  - Remove recipient id poroperty
- [x] Modify EmailNotificationResultType.cs
  - Add Failed_RecipientReserved
- [x] Modify SmsNotificationResultType.cs
  - Add Failed_RecipientReserved

__Database__
- [x] Stop using recipientIid in functions and procedures
-  [x] Modify table emailnotifications
   - Add column recipientorgno
   - Add column recipientnin (nationalidentitynumber)
   - Remove column recipientid
-  [x] Modify table smsnotifications
   - Add column recipientorgno
   - Add column recipientnin (nationalidentitynumber)
   - Remove column recipientid
- [x] Extend type `emailnotificationsresulttype`
  - Add enum value `Failed_RecipientReserverd`
- [x] Extend type `smsnotificationsresulttype`
  - Add enum value `Failed_RecipientReserverd`
- [x] Modify procedure _insertemailnotification_
  - Add input parameter recipientorgno
  - Add input paramter recipientnin
  - Remove input parameter recipientid
- [x] Modify procedure _insertsmsnotification_
  - Add input parameter recipientorgno
  - Add input paramter recipientnin
  - Remove input parameter recipientid
- [x] Modify function getsmssummary return table
  - add  recipientorgno
  - add recipientnin
  - remove recipientid
- [x] Modify function getemailsummary return table
  - add  recipientorgno
  - add recipientnin
  - remove recipientid
- [x] Modify function getemailrecipients return table
  - add  recipientorgno
  - add recipientnin
  - remove recipientid
- [x] Modify function getsmsrecipients return table
  - add  recipientorgno
  - add recipientnin
  - remove recipientid
__Repository__
All repository classes must be modified to reflect the changes made to the tables, functions and procedures. 
- [x] Stop writing recipientIid to tables
- [x] EmailNotificationRepository
- [x] SmsNotificationRepository

__General tasks__
- [x] Add / modify unit tests
- [x] QA
- [x] Update swagger in docs
- [x] Regression test
- [x] Manual test: add national identity number for recipient manually in database

## Acceptance criteria
- [x] Regression tests are successful
- [x] If person number or organisation number if defined in database, it should be exposed through the GET endpoint wherever the recipient object is included
