### ISSUE TITLE
Add logic for generating notifications from national identity number

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#437]
## Description

An application owner may specify only the national identity number of the recipient of a notification. Altinn Notifications should support retrieving requried contact details and generating a notification based of this information. 

## Considerations

- [x] What should we name the property where application owner states that they want to bypass the reservation in KRR? 
  - IsReservable
  - **IgnoreReservation**
  - BypassReservation
 
- [x] Should IgnoreReservation be linked to the order as a whole or to the recipient? 
  - To the order. So should the appId or service affiliation once its implemented. 

- [x] Should the lookup and notification generation be done synchronously or async? 
  - Synchronously 

- [ ] Should the persistence of the notifications linked to an order be done in a single transaction post a full table with the necessary data? Would simplify retry logic. 

## Tasks
- [x] add new IgnoreReservation property to NotificationOrderRequest and NotificationOrder domain models
- [x] Implement a service and/or client for retrieving contact information and reservation flag from Altinn Profile based on person number
- [x] Add input parameter to  EmailNotificationService.CreateNotification specifying if notification can IgnoreReservation
- [x] Add input parameter to  SmsNotificationService.CreateNotification specifying if notification can IgnoreReservation
- [x] Extend EmailNotificationService.CreateNotification with logic for retrieving email address if only person number is defined
- [x] Extend SmsNotificationService.CreateNotification with logic for retrieving mobile number if only person number is defined
- [x] Alter ProcessOrderRetry methods in both services to support the address lookup case. Check if notifications is generated for national identity number
- [x] Update values.yaml with new env variables

## Acceptance criteria
- [x] If the person has reserved themselves from digial communication a notification is persisted in the database with status Failed_RecipientReserved
- [x] If a contact point is found for the provided person number a new notification is persisted in the database with status NEW
- [x] If a recipient has defined a national identity number and a contact point, no lookup of contact information should be 
done
- [ ] if the order has specified buypass of reservation a new notification is generated regardless of the reservation of the user
- [x] If there is no contact point available for the end user a notification is persisted in the database with status Failed_RecipientNotIdentified

## Test

- Profil for **TRU HYLLE** f.nr. **108599 99587**
  - Both email and phone number has been set and it is Khan's. No reservation.
  
- Profil for **SIKKER SALAMANDER** f.nr. **098101 47471**
  - No contact information. Reserved from communication.

**Comment by codemascot** [comment]
I think I found a bug. 🤔 When testing for user with `23094190088` ID and calling the below endpoint:
```
GET https://platform.at22.altinn.cloud/notifications/api/v1/orders/99a0aa49-5d26-4cbb-9f07-7bdb1677d098/notifications/sms
```
I'm getting 404 Not Found response. 

I have verified that the order ID exists from the other GET endpoints with the same order ID. 🤔

**Comment by codemascot** [comment]
I think we have found another bug regarding the `ignoreReservation` parameter. When testing with `30056380007` ID we found that the value of `ignoreReservation` is not getting stored. 🤔 
```
POST https://platform.at22.altinn.cloud/notifications/api/v1/orders/email
GET https://platform.at22.altinn.cloud/notifications/api/v1/orders/974b0a81-506e-45a9-aa3c-07446dd3e3b5
```

**Comment by acn-sbuad** [comment]
- Could not reproduce 404 bug.
- #493 fixes the ignoreReservations issue.
