### ISSUE TITLE
Add calculation of sms count during notification generation

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#440]
### Description

LinkMobility does not expose the number of segments throught the Gateway that we are using, and we will have to calculate this ourselves in order to bill our clients for the right number of SMS. 

Rule set for segment calculation

`For sending, the message length should not exceed 160 characters unless you would like to use concatenated SMS messages. Messages exceeding 160 characters will be split up into a maximum of 16 SMS messages, each of 134 characters. Thus, the maximum length is 16*134=2144 characters. This is done automatically by the SMS Gateway. Messages of more than 2144 characters will be truncated. The message must/will be URL-encoded`

### Tasks

- [x] Add calculation of message length to notification generation either in database or service logic
- [x] Adjust metrics function `getmetrics` to return total number of smscount instead of number of sms notifications
- [x] QA
- [x] Manual test

### Acceptance Criterias

- [x] Sms count is populated for all new notifications in the database
- [ ] Sum of sms count property is what is exposed by the metrics view
