### ISSUE TITLE
Regression and use case tests - NIN lookup

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#441]
## Description

Our automated tests should include test cases for address lookup. 

## Tasks
- [x] Register email for use case test users (will require setting up bank id for test users to be able to log into KRR and add contact email: finnesikke@digdir.no)
- [x] Identify a person that is reserved.
- [x] Implement k6 test for notification order with email as communication channel to test user through national identity number
- [x] QA 

## Acceptance criteria
- [x] Working use case test using nin as input
- [x] Failures are correctly reported to slack
