### ISSUE TITLE
Create a new endpoint for contact information of an organisation in SblBridge

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#442]
### Description
The official contact information for an organisation is currently maintained and kept in Altinn 2. To access the data from Altinn 3 we need to create a new lookup endpoint in SblBridge.

The endpoint needs to use data from Register. Specifically the KoFuVi services. It should be possible to retrieve the information for multiple organisations at the time.

### Tasks
- [x] Create a new consumer for unit contact information
- [x] Create a new controller for unit contact information
- [x] Create an input model that can hold lookup parameters like the organisation numbers
- [x] Create a model for unit profile that can hold official contact information
- [x] Create a new endpoint for lookup of official contact information
- [ ] Optional: Create a few Bruno tests of the endpoint for manual testing

__General tasks__
- [x] Add / modify unit tests
- [x] QA
- [x] Regression test
- [x] Manual test

### Testing
POST  /register/api/organizations/contactpoints

```json
{
"organisationNumbers":["123456", "123456"]
}
```
### Acceptance criteria
- [ ] All tasks above have been completed
- [ ] Endpoint returns correct contact information for the given organisations

**Comment by SandGrainOne** [comment]
Tested in at22. Looks like there is a bug in mapping. Instead of returning the full email address it's only returning the username part of the address. 
```
{
    "contactPointsList": [
        {
            "organisationNumber": "312508729",
            "emailList": [
                "terje.holene"
            ],
            "mobileNumberList": []
        }
    ]
}
```

**Comment by SandGrainOne** [comment]
Tested ok
