### ISSUE TITLE
Create a new endpoint for personal contact information for an organization in SblBridge

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#449]
### Description
The personal contact information that users can register for an organisation is currently maintained and kept in Altinn 2. To access the data from Altinn 3 we need to create a new lookup endpoint in SblBridge.

The endpoint needs to use data from Profile. Specifically the unit profile services. It should be possible to retrieve the information for multiple organisations at the time.

### Consideration
- Er det rart å ikke sjekke rollekravet når vi skal sende ut varsel til brukere som har registrert kontaktpunkt for org? Gir det mening at regnskapsfører skal informeres om en frist som ikke angår dem f.eks? Er det reelt at noen sender ut et varsel til virksomhet uten at det er tilknyttet en eller annen form for tjeneste som og har definert noen rollekrav? Et eller annet krav må vi vel autorisere mot så vi vet at de enda har en rolle for orgen og, eller blir notification endpoint slettet automatisk når man mister en rettighet?

### Specification

SBL
InternalUserProfileProxy.GetReporteeNotificationEndPointsForReportee
- Returns a list of notification endpoints  will get all notification endpoints for the partyId for the organization

 

### Tasks
- [x] Create a new consumer for personal contact information for an organisation
- [x] Create a new controller for personal contact information for an organisation
- [x] Create an input model that can hold lookup parameters like a list of organisation numbers
- [x] Create a model for unit profile that can hold personal contact information
- [x] Create a new endpoint for lookup of personal contact information
- [x] Optional: Create a few Bruno tests of the endpoint for manual testing

__General tasks__
- [x] Add / modify unit tests
- [x] QA
- [x] Regression test
- [x] Manual test

### Acceptance criteria
- [x] All tasks above have been completed
- [x] Endpoint returns correct contact information for the given organisations

**Comment by acn-sbuad** [comment]
Verified in at22.
Request body:   ["989271156", "989271157", "989271153"]
Response body: 
[
  {
    "PartyId": "18dffb14-28e6-46f4-be2e-795cd75ece4c",
    "LegacyPartyId": 51206047,
    "OrganisationNumber": "989271156",
    "ContactPoints": [
      {
        "LegacyUserId": 20000000,
        "Email": "",
        "PhoneNumber": "99315829"
      }
    ]
  }
]
