### ISSUE TITLE
Altinn 3 endpoint for official contact information for organisation in Register

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#450]
### Description
Official contact information for an organisation needs to be available through the Register application. Expand the application to include an endpoint that can return this information for a given organisation.

Address to sbl: https://at22.altinn.cloud/sblbridge/register/api/organizations/contactpoints

### Tasks
- [ ] Define a new model for the official contact information of an organisation.
- [ ] Add or update a SblBridge client to interact with Altinn 2 to retrieve the official contact information.
- [ ] Add a controller for organisation profiles
- [ ] Add to controller a new endpoint that can return the official contact information of an organisaion

__General tasks__
- [ ] Add / modify unit tests
- [ ] QA
- [ ] Regression test
- [ ] Manual test

### Acceptance criteria
- [ ] All tasks above have been completed
- [ ] Endpoint returns correct contact information for the given organisations
