### ISSUE TITLE
Altinn 3 endpoint for personal contact information associated with organisation in Profile

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#451]
### Description
Personal contact information associated with an organisation needs to be available through the Profile application. Expand the application to include an endpoint that can return this information for a given organisation.

### Consideration
-  If SBL returns mobile number without country code, norwegian country code should be added to number

### Tasks
- [x] Define a new model for the personal contact information associated with an organisation.
- [x] Add or update a SblBridge client to interact with Altinn 2 to retrieve the contact information.
- [x] Add a controller for organisation profiles
- [x] Add to controller a new endpoint that can return the contact information associated with an organisaion
    - [x] Endpoint should be able to filter contact endpoints base on given resource.

__General tasks__
- [x] Add / modify unit tests
- [x] QA
- [ ] Regression test
- [x] Manual test

### Acceptance criteria
- [x] All tasks above have been completed
- [x] Endpoint returns correct contact information for the given organisations
