### ISSUE TITLE
Add logic to search for contact details of main unit when there are none on a sub unit

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#455]
### Description
This issue include some analysis of current functionality in Altinn 2 and possible KoFuVi. Should Register return the contact details of the main unit of a sub unit without contact details? If so then implement necessary changes.

### Tasks
- [x] Find out if this issue is something we need to do or not. Investigate whether this is existing logic in Altinn 2 and KoFuVi.
  - This is existing logic in 2.0
- [x] Update service logic in Register to search for contact information of main unit if current organisation is a sub unit without contact information
- [x] QA
- [ ] Documentation
- [x] Manual testing

### Acceptance criteria
- [x] Register will return the contact information of the main unit of a sub unit without contact information

**Comment by acn-sbuad** [comment]
This was implemented as a part of #442 and is handled in the altinn 2 register logic. Info for main unit will be returned if non exist for the sub unit.

**Comment by SandGrainOne** [comment]
Tested ok
