### ISSUE TITLE
Add logic for generating notifications based on organisation number

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#456]
### Description
Add logic to the service logic of notification to support recipient of type organisation number. Use the services already implemented and rewire the logic to include contact information lookup of both official and personal contact information. Make sure the notifications are stored with identified contact information.

### Tasks
- [ ] Add contact information lookup to the service logic handling new notification orders
- [ ] Unit tests
- [ ] Review

### Acceptance criteria
- [x] Notification can handle a notifications order with an organisation number by finding the official contact details of the organisation.
- [x] Notification summary should include both organization number and email or mobile number of org recipient
- [x] If an official contact number is not registered the response when placing the order should indicate this
- [x] If an official contact email /number is registered the order should be accepted and processed
- [x] If an official contact email/number exists at the point of placing the order, but not when the notification is to be sent, it should result in recipient not identified status in the notification summary
- [x] If an organisation has multiple official contact points, one notification should be generated per contact point.

**Comment by acn-sbuad** [comment]
testing in AT22. 
Looking at the notification details for a sent order, I believe orgNo should be included in the recipient field. For service owner to know which org the email address and sent email is linked to. 

```json
    "notifications": [
        {
            "id": "68758e07-05b6-490b-b065-89f231000e75",
            "succeeded": false,
            "recipient": {
                "emailAddress": "4tw8bgez@jei5wp6wx.no"
            },
            "sendStatus": {
                "status": "New",
                "description": "The email has been created, but has not been picked up for processing yet.",
                "lastUpdate": "2024-05-07T15:37:02.193146Z"
            }
        }
    ]
```

**Comment by SandGrainOne** [comment]
Testing sending in the future with missing contact information at the send time: 
OrderId: "152ce64b-fdcf-4d82-bf78-d2e74faac88e"
RequestedSendTime: "2024-05-28T14:30:00+02:00"
Organization: 312508729

Manually deleted the contact information

**Comment by SandGrainOne** [comment]
AT24

Something wierd with order: 5b3c624f-a868-4e51-8d5f-928179669155

{{BasePath}}{{PortNumber}}/notifications/api/v1/orders/{{NotificationOrderId}}/status
Reports succeeded: 0
while
{{BasePath}}{{PortNumber}}/notifications/api/v1/orders/{{NotificationOrderId}}/notifications/email
Reports succeeded: 1
This would be the expected number. Why is it different?

**Comment by SandGrainOne** [comment]
Testing completed
