### ISSUE TITLE
Configuration of platform application accesses through workload identity

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#486]
### Description

Configure the access rights for each platform application so that each application have access to everything they need through workload identity. This is to replace existing use of explicit access like user name and password and shared access keys.

```[tasklist]
### Tasks
- [ ] Threat modeling
- [ ] https://github.com/Altinn/altinn-platform/issues/694
- [ ] https://github.com/Altinn/altinn-platform/issues/701
- [ ] https://github.com/Altinn/altinn-receipt/issues/264
- [ ] https://github.com/Altinn/altinn-profile/issues/141
- [ ] https://github.com/Altinn/altinn-register/issues/185
- [ ] https://github.com/Altinn/altinn-storage/issues/363
- [ ] Identify and configure necessary accesses for Notifications
- [ ] Identify and configure necessary accesses for Events
```
