### ISSUE TITLE
Add national identity- and organization number lookup to localtest 

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#496]
### Description
Expand Localtest with new business logic being developed on Notifications for national identity- and organization number.
Currently no support in apps, so should be tested via postman. 

### Tasks
- [x] Look through the endpoints already added and add the missing service logic.
    - [ ] Modify the model(s) to support national identity number
    - [ ] Modify the model(s) to support organization number
    - [ ] Modify validation.
- [x] Review (QA)
- [ ] Documentation
   - [ ] What is the difference between the feature set in localtest vs. real environment.
   - [ ] Find a suitable place to have such documentation

### Acceptance criteria
- [ ] An App can order a notification without getting any errors.

**Comment by acn-sbuad** [comment]
Blocked until app template supports generating notification order requests with only national identitiy number or person number

**Comment by acn-sbuad** [comment]
Team Apps have been informed of the new features on our side, and will be adding support for this. Still blocked until solved by Team Apps.

**Comment by acn-sbuad** [comment]
No clear need for documentation when checking with app migration team. Closing without completing documentation.
