### ISSUE TITLE
Regression and use case tests - OrgNo lookup

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#507]
## Description
Expand the k6 tests to include verification of address lookup when recipient is an organization.

## Tasks
- [x] Generate or identify test data for address lookup with organisation number 
 
## Acceptance criteria
- [ ] Use-case tests include a verification of address lookup of an organization. 
- [x] Regression tests include a verification of address lookup of an organization.

**Comment by SandGrainOne** [comment]
Fulfilled by #510
