### ISSUE TITLE
Adjust business logic to accomodate handling notifications with app affiliation to an organization.

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#508]
### Description
Make sure that any logic related to creating notifications can handle all the permutations correctly.

- Notifications without app affiliation
    - Official Contact information only
- Notifications with app affiliation
    - Official contact information and personal contact information (Access based recipient filtering.)

### Consideration
- if an order is placed with resourceID and national identity number, what should the course of action be? Send notification, but no lookup past contact points for NIN, or reject order as invalid? 
- should we removed duplicate contact points before generating the notifications? 
- 

### Tasks
- [x] Add the profile lookup to find potential recipients based on personal contact information
- [x] Add access based filtering to the list of persons with contact information
- [x] Review (QA)
- [x] Unit and integration tests
- [x] Manual tests
- [x] Documentation

### Acceptance criteria
- [x] Placing a notification with app affiliation order to an organization results in notifcations to persons with personal contact information.
- [x] If resource is included notification is sent to official contact point and all authorized user registered contact points
- [x] Recipient lookup is successful if official contact point is available and no user registered contact points are available, 
- [x] Recipient lookup is successful if at least one user registered contact point and no official contact point is available
