### ISSUE TITLE
Add regression and use case tests that include an app affiliation

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#510]
## Description
Expand the k6 tests to include verification of address lookup when recipient is an organization. The test should include app affiliation to test the lookup for personal contact information. This should also make it unnecessary to keep the NIN lookup test as both Register and Profile will be included in this new test.

We can use the ttd apps-test app for testing app affiliation. Might need to adjust policy.

## Tasks
- [x] Generate or identify test data for address lookup with organisation number that includes an app affiliation.
 
## Acceptance criteria
- [x] Use-case tests include a verification of address lookup of an organization. 
- [x] Regression tests include a verification of address lookup of an organization.
- [x] Remove the NIN lookup test from the use-case test. (Keep it for the regression test.)
