### ISSUE TITLE
Add an implementation guide for sending notifications without app affiliation to an organisation

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#511]
### Description
Update documentation to include the latest changes for notifications. Architecture etc. Add an implementation guide for how to use the feature. Guide for sending notifications without app affiliation.

### Tasks
- [x] Update architecture documentation
- [x] Add an implementation guide.
- [x] Review (QA)

### Acceptance criteria
- [x] Developers at application owners can find good help on how to implement a notifications client
