### ISSUE TITLE
Add an implementation guide for sending notifications with app affiliation to an organisation

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#512]
### Description
Update documentation to include the latest changes for notifications. Architecture etc. Add an implementation guide for how to use the feature.

### Tasks
- [x] Update architecture documentation
- [x] Add an implementation guide.
- [x] Document address lookup. Maybe in the user guide section? 
- [x] Review (QA)

### Acceptance criteria
- [x] Developers at application owners can find good help on how to implement a notifications client
