### ISSUE TITLE
Analysis: Look into alternatives to Kafka for a more suitable system for the internal needs of Notifications

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#513]
### Description
Kafka was not a very good match with what Notification needs. In this issue we should work on finding a suitable replacement. A part of this tasks is to take input and experiances from other teams with similar needs.

### Additional Information

Dialogporten and Authorization is picking Azure Service Buss and using Mass Transit.

https://www.youtube.com/@nickchapsas/search?query=mass%20transit

### Tasks

- [ ] Collect experiences other teams are having with their choices.
- [ ] List pros and cons
    - [ ] Hosting options
    - [ ] Costs
- [ ] Arrange a heated debate

**Comment by olebhansen** [comment]
Closing as not prioritized. We need external discussions to mature before a change is required. #544 was created to prepare and uncover any blockers for refactoring to the (assumed to be) least complex solution.
