### ISSUE TITLE
Add business logic to send notifications to recipient identified with national identity number regardless of resource affiliation.

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#524]
### Description
Add support for app or resource afiliation to notification orders where recipient is a person. Resource or App affiliation in a notification order should not affect the order in any way or limit the recipients. Logic should do KRR lookup as without app affiliation and work as is.

### Tasks
- [x] Start by testing. Everything might already be working,
- [x] Adjust logic as needed if anything is preventing notifications order from being processed and stored correctly.

### Acceptance criteria
- [x] It's possible to give a notification order a resource affiliation.
- [x] Orders with resource affiliation is processed correctly and notification(s) are being sent.

**Comment by acn-sbuad** [comment]
Testing locally during dev of support for resource and orgnumber seems nothing requires changing to support adding resource when sending to a national identity number.

**Comment by acn-sbuad** [comment]
Verified in at22. Resource is persisted on order, but does not affect lookup in any way
