### ISSUE TITLE
Notifications should be sent during Altinn's send window

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#538]
### Description

SMS should not be sent out during night time etc. 

In Altinn 2 the send window is 9 AM to 515 PM. The SMS is then sent at the first opportunity when the window opens again. 
We do not refuse send orders with a requested send time outside the window.

In Altinn 3 we use a cron job to trigger the sending of SMS. To adhere to the send window the cron trigger can be modified to only trigger in the send window. This way we do not put additional load on our API or other parts to have them evaluate if we are within the send window or not. 
 

### Considerations
As a job in AKS cannot have to different schedules we have two options, we could modify the send window to 9AM to 5PM
or have two cron jobs set up. One to handle 9AM-4:59PM and one to handle 5:00PM to 515 PM. 

"* 9-16 * * *"  This part runs your command every minute from 9:00 AM to 4:59 PM.
"0-15 17 * * *" This part runs your command every minute from 5:00 PM to 5:15 PM.

 Do we want to modify the send window or have two cron jobs? 
 
additional 15 minutes in Altinn 2 is to support logic in code and not limit sending until 5PM. Send window is 9 - 5. 

### Additional Information

Altinn 2 has the option of not sending SMS on holidays, but this has never been activated and an SMS can be sent any day as long as it is within the send window. 

```xml
    <!-- Notification Settings-->
    <add key="Notification_SendDays" value="Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday,Holiday"/>
    <add key="Notification_SendTimeStart" value="09:00"/>
    <add key="Notification_SendTimeEnd" value="17:15"/>
```
### Tasks

- [x] Adjust cron schedule for SMS trigger job
- [x] QA
- [x] Manual test
- [x] Document the send window on docs and in architecture documentation. 

### Test cases
| req. send time | received|
|-----|----|
| "2024-06-26 09:18:35+00"| 09:18 |
|"2024-06-26 08:18:35+00"| 09:00 |
|"2024-06-25 18:18:35+00"| 09:00 |
|"2024-06-25 17:18:35+00"| 09:00 |
|"2024-06-25 16:18:35+00"| 16:18 |
|"2024-06-25 10:18:350"| 10:19|

### Acceptance Criterias

- [x] It is possible to place notifciation orders outside of the send window
- [x] If requested send time is before 9 AM, an sms is not sent until 9 AM
- [x] If requested send time is after 5 PM an sms is not sent until 9 AM
