### ISSUE TITLE
Support for placeholder keywords for dynamic changes in texts based on recipient

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#545]
### Description

We want the Notifications service to have solid support for having multiple independent recipients in a single order. This means the texts needs to have some basic support for personalization based on recipient. Like addressing the recipient by name. 

There needs to be way for service owners to make smaller recipient specific adjustments to the content of notifications. The feature here should be a search and replace in texts

Keywords copied from Altinn 2 and adjusted for Altinn 3:

Keyword                             | Description
------------------------------|-----------------
`$recipientFirstName$`       | The first name of a person *
`$recipientMiddleName$`   | The middle name of a person  *
`$recipientLastName$`        | The surname of a person *
`$recipientName$`              | The full name of the recipient, support both person and organization.
`$recipientNumber$`          | The organization number when recipient is an organization. Left empty if recipient is a person.

* Support for first and middle name is postponed untill we have a propper data source. 

#### Example
A simple request with personalized texts:
```
{
    "subject": "Happy birthday $recipientFirstName$!",
    "body": "Hi $recipientFirstName$, remember to never click any links in emails!",
    "recipients": [
        {
            "nationalIdentityNumber": "18874198354"
        }
    ]
}
```

There is a new specialized endpoint in Register that should provide what we need:
register/api/v1/parties/nameslookup
See issue: #593 

### Additional Information

The source of the keyword list above is inspired by Altinn 2 documentation: [List of `Varselmakroer`](https://altinn.github.io/docs/api/tjenesteeiere/#varselsmakroer). The list is curated down to a list of keywords actually being used in Altinn 2.

### Refinement
- We can perform the lookup and macro replacements during the order processing. The final texts is added to the generated notifications being written to Kafka topics.
- It's difficult to validate that all keywords in texts are actual keywords for replacement. We'll assume that the application owners will test their texts and fix mistakes like missing $ symbols or typos.
- Investigate if there is a library we can use. Templating/macro.

### Tasks
- [x] Verify that the `$recipientEmail$`<br/> `$recipientMobileNumber$` are actually in use before implementing support
- [x] Investigate available templating/macro libraries
  - [x] Library needs to add value outside search and replace of text
  - [x] Can we use the defined keywords or does the library require a different format
- [x] Implement necessary clients for obtaining the Party/Person/Organization objects
  - [x] Some data might already be available through existing clients
  - [x] Add caching of the data where appropriate for easy reuse between lookup and keyword replacement
- [x] Unit/integration tests
- [x] Include a keyword in one of the existing use-case/regression tests
- [x] Documentation
- [x] Review
- [ ] Prepare and concuct demo (Altinn internal demo, Friday 13th)

### Acceptance criteria
- [x] Original texts is stored without changes including keywords
- [x] Keywords in notification texts are being replaced by the correct values in the final notification(s)
- [x] Documentation includes information about keywords and how they can be used

**Comment by olebhansen** [comment]
Pending a suitable endpoint to surce data from (#589)

**Comment by SandGrainOne** [comment]
Updated the list of keywords we're going to support after the #604 analysis.

**Comment by Ahmed-Ghanam** [comment]
**26.11.2024**  
During a meeting to assess our requirements, we made the following decisions:  
- Placeholder replacement values will not be stored in the database, as this is not necessary for now.  
- Initially, we will support only the `$recipientName$` and `$recipientNumber$` placeholders. Other keywords can be implemented in the future if required.

**Comment by olebhansen** [comment]
FYI, some tests from team "Melding og Formidling": https://digdir.atlassian.net/wiki/spaces/BF1/pages/2798256130/Melding+med+varsling

**Comment by Ahmed-Ghanam** [comment]
The documentation has been updated and here is the pull request https://github.com/Altinn/altinn-studio-docs/pull/1951

**Comment by Ahmed-Ghanam** [comment]
The planning and implementation stages of this task took longer than expected because of the need to handle edge cases. I updated the size from `L` to `XL`

**Comment by Ahmed-Ghanam** [comment]
### Test Outcome: 15.01.2025

#### Use Case Tested:
The following notification order was tested:

```json
{
  "sendersReference": "order-email-with-keywords",
  "recipients": [
    {
      "organizationNumber": "313600947"
    },
    {
      "nationalIdentityNumber": "01124801679"
    },
    {
      "emailAddress": "ahmed.ghanam@digdir.no"
    }
  ],
  "ignoreReservation": true,
  "notificationChannel": "Email",
  "emailTemplate": {
    "fromAddress": "noreply@altinn.cloud",
    "subject": "Hello $recipientName$! Test Email",
    "body": "Hi $recipientName$, this Email is tailored for $recipientNumber$.",
    "contentType": "Plain"
  }
}
```

#### Expected Outcome:
Notifications should be sent via email with keywords `$recipientName$` and `$recipientNumber$` replaced with recipient-specific data.

#### Actual Outcome:
The results were as expected:

1. **Recipient - `organizationNumber: 313600947`**
   ![Outcome Image](https://github.com/user-attachments/assets/e039da41-c700-4b44-a16d-f33a49661619)

2. **Recipient - `nationalIdentityNumber: 01124801679`**
   ![Outcome Image](https://github.com/user-attachments/assets/906a2090-17ba-4df2-b045-5ccf1724bf60)

3. **Recipient - `emailAddress: ahmed.ghanam@digdir.no`**
   ![Outcome Image](https://github.com/user-attachments/assets/75980259-a2d6-4cb3-ab13-1e71f9931c7c)

**Comment by SandGrainOne** [comment]
Tested lookup for person name and organization name for both email and sms. Looks good.
