### ISSUE TITLE
Reject any order with links in texts

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-notifications#573]
### Description

To prevent any user of notification to send links in notification, any orders with links should be rejected.

### Additional Information

- @tba76 checks if there are existing libraries to leverage (possibly in use in Altinn studio and in "fluent validation")
- Response-code: 400 "Bad request"
- Return a problem-detial listing the fields that are invalid
- Extend existing validation-pipeline

### Tasks
- [ ] Development
- [ ] Implement unit tests
- [ ] QA
- [ ] Review documentation to see if updates are required

### Acceptance Criterias
- [x] An order containing an sms template with a link should result in a 400 response
- [x] An order containing an email template with a link should result in a 400 response
- [x] An order containing both an email and sms template with links should result in a 400 response.
- [x] Encoded links should also result in a 400 response

**Comment by olebhansen** [comment]
AFAIK, this replicates as-is functionallity.

**Comment by SandGrainOne** [comment]
Tested and approved.
