### ISSUE TITLE
Regression testing of Notifications with Profile configured to use local KRR cop as data source

### ISSUE THREAD

**Issue by olebhansen** [Altinn/altinn-notifications#616]
Blocked by https://github.com/Altinn/altinn-profile/issues/176

Once our new KRR replica is available, we should refactor notifications to use this as a datasource in applicable cases (when the recipient is a person identified by SSN).

### Tasks
- [ ] Check if Altinn 2 is using the KRR dates: "updated" and "verified" and how if so.
- [x] Ensure that Notifications handles the newly declared "nullability" in properties UserId, NationalIdentityNumber, MobileNumber, and Email
- [x] Test order creation that involves users having null-values for UserId, NationalIdentityNumber, MobileNumber, and/or Email

### Acceptance criteris:
- [x] Notification uses Altinn3 KRR replica when this is the only datasource needed (persons by SSN)

### Things to discuss
- **Threat modelling**
Discuss possible security issues
- **Documentation**
- [ ] Do we need to update documentation in altinn docs?
- [ ] Do we need Internal documentation (confluence)?
- [x] We do not need to update documentation or write internal documentation
- **External tests**
- [ ] Should new functionality be Regression tested?
- [ ] Should new functionality be included in Usecase tests?
- [x] Do not need to update automated tests
- **Acceptance criteria**
Does the issue have defined acceptance criteria?
