### ISSUE TITLE
Authorization requirements for different aspects of the notification system

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-notifications#8]
## Description
We need to add authentication so it is possible to authorize senders of notification.

## Consideration
- Can we simplify authorization when creating a notification from an Altinn App? Require access token? 
- Should all app owners have access or is this an extra? 
    - Separate scope for different notification channels? SMS cost extra?
- Do we need to involve legal 

## Analysis
 - scope required for app owners using api directly
 - accestoken required for app both on post and get

**Scopes** 
altinn:notifications.create
altinn:notifications.{admin or config}

**Endpoints**
/trigger: not exposed, no authorization required
/orders: accessstoken or scope altinn:notifications.create
~~/org/config: accesstoken or scope altinn:notifications.{admin or config}. We should verify that claim in token matcg org you are modifying for or represents Altinn Studio, we will trust Altinn Studio to limit access to relevant organisations.~~

## Tasks
- [x] Configure authentication in notification component
- [x] QA
- [x] Test
  - [x] POST order/email with scope
  - [x] POST order/email with accesstoken (maybe set up a temp function to support this?)
  - [x] POST order/email without scope or accesstoken
  - [x] GET order/id with scope
  - [x] GET order/id with accesstoken 
  - [x] GET order/id withour scope or accesstoken
  - [x] GET order?sendersRef with scope
  - [x] GET order?sendersRef with accesstoken 
  - [x] GET order?sendersRef withour scope or accesstoken

## Acceptance criterias
- [x] Trigger endpoint does not require scope
- [x] POST order/email endpoint requires scope altinn:notifications.create or accesstoken
- [x] GET order/{id} endpoint requires scope altinn:notifications.create or accesstoken
- [x] GET order?sendersRef requires scope altinn:notifications.create or accesstoken

**Comment by SandGrainOne** [comment]
Testing completed.
